// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9WyDgNrP6jO-NIoCWJlWEKehzMtYBjo',
    appId: '1:396573352249:web:8f63dad05ed3d546de08e8',
    messagingSenderId: '396573352249',
    projectId: 'insta-clone-4fe40',
    authDomain: 'insta-clone-4fe40.firebaseapp.com',
    storageBucket: 'insta-clone-4fe40.appspot.com',
    measurementId: 'G-6KG2MSD8XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwhv0RMdlKNEu2JQ192aUHVc9ijmsA0TE',
    appId: '1:396573352249:android:780707c7176e7ba3de08e8',
    messagingSenderId: '396573352249',
    projectId: 'insta-clone-4fe40',
    storageBucket: 'insta-clone-4fe40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRV2lXEe2NbKAhiWVTdjcZMqXTm-j3B8',
    appId: '1:396573352249:ios:87779e9b04891b48de08e8',
    messagingSenderId: '396573352249',
    projectId: 'insta-clone-4fe40',
    storageBucket: 'insta-clone-4fe40.appspot.com',
    iosClientId: '396573352249-ikh16k5go19ob1qu9elbc7iofllncj2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
